# Ruta base
data.path=data/

app.language=es

# Archivos
person.file=persons.csv
product.file=products.csv
accounting.file=accounting.jsonl

# Paginado
page.size=10

# Alineación de tablas
table.align=LEFT

# Longitudes de nombre y apellido
person.name.min=2
person.name.max=10
person.lastname.min=2
person.lastname.max=10

# Estilo de descripción de productos
# Valores válidos: UPPERCASE (TODO EN MAYÚSCULAS) / TITLECASE (Primera Letra De Cada Palabra)
product.description.style=TITLECASE

person.birthdate.min=1900-01-01