# Ruta base
data.path=data/

# Archivos
person.file=persons.csv
product.file=products.csv
accounting.file=accounting.jsonl

# Paginado
page.size=5

# Alineación de tablas
table.align=LEFT

# Longitudes de nombre y apellido
person.name.min=2
person.name.max=5
person.lastname.min=2
person.lastname.max=5

# Estilo de descripción de productos
# Valores válidos: UPPERCASE (TODO EN MAYÚSCULAS) / TITLECASE (Primera Letra De Cada Palabra)
product.description.style=TITLECASE