data.path=data/

app.language=en

person.file=persons.csv
product.file=products.csv
accounting.file=accounting.jsonl

page.size=5

table.align=LEFT

person.name.min=2
person.name.max=5
person.lastname.min=2
person.lastname.max=5

product.description.style=TITLECASE