data.path=data/

app.language=es

person.file=persons.csv
product.file=products.csv
accounting.file=accounting.csv

page.size=5

table.align=LEFT

person.name.min=2
person.name.max=5
person.lastname.min=2
person.lastname.max=5

product.description.style=TITLECASE

person.birthdate.min=2000-01-01